# Generated by Django 5.1.6 on 2025-07-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='pronunciation',
        ),
    ]
